spring.application.name=exercise-counter
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=exercisecounter
spring.datasource.password=V2g0-f8S(sQ
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8090