version: '3.9'

services:
  postgreDb:
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: exercisecounter
      POSTGRES_PASSWORD: V2g0-f8S(sQ
      POSTGRES_DB: db
      TZ: "UTC"

volumes:
  pgdata: